# yaml file for node js j

name: Sample Node js Applications
on:
  push:
    branches:
      - '*'

jobs:
  node-js-demo:
    runs-on: [self-hosted, linux, x64]
    steps:
      
      - run: pwd
      - run: ls
    
#      - uses: actions/checkout@v3
      - run: git checkout ${{ github.head_ref }}
      - run: npm install
      - run: pm2 delete node
      - run: PORT=2022 pm2 start "npm start" --name node
