# yaml file for node js j

name: Sample Node js Applications
on: [push]

jobs:
  node-js-demo:
    runs-on: [ self-hosted, linux, x64 ]
    steps:
      - name: started
      - run: pwd
      - run: ls

 #      - name: execute
 #     - uses: actions/checkout@v3
 #     - run: git checkout ${GITHUB_REF#refs/heads/}

     # - run: npm install
     # - run: pm2 delete node
     # - run: pm2 start "npm start" --name node

