# yaml file for node js

name: Sample Node js Applications
on:
  push:
    branches:
      - '*'

jobs:
  node-js-demo:
    runs-on: self-hosted
    steps:
      - name: started
      - run: |
        pwd
        ls

      - name: execute
      - run: git checkout ${GITHUB_REF#refs/heads/}

      - run: npm install
      - run: pm2 delete node
      - run: pm2 start "npm start" --name node

