# yaml file for node js j

name: Sample Node js Applications
on:
  push:
    branches:
      - '*'

jobs:
  node-js-demo:
    runs-on: self-hosted
    steps:
      
    - name: Git pull
      run: git stash && git pull
